# Site settings
title: zhenke blog
email: zhenkyle@gmail.com
description: "This my awesome blog."
baseurl: ""
url: "http://zhenkeblog.cn"

# Build settings
markdown: kramdown
permalink: pretty

# Added by ZK
source: ./src
destination: ./build
